services:
  apache:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf

  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database

  database:
    image: mariadb:10.5
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ramen
      MYSQL_USER: maria
      MYSQL_PASSWORD: admin
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  dbdata:
