services:
  database:
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_USER: maria
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 0
    depends_on:
      - database
  vite:
    image: node:24-slim
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/html
      - node_modules:/var/www/html/node_modules
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  node_modules:
